#!/bin/bash

create_export_folder() {
    mkdir exports
}

render_manimation() {
    local py_file=$1
    local res_ratio=$2
    local show_preview=$3
    local chosen_res="1920,1080"
    
    case $res_ratio in 
    16:10)
        chosen_res="1920,1200"
        ;;
    esac
    
    if [ "$show_preview" = true ]; then
        manim -pqm $py_file -r $chosen_res
    else
        manim -qm -r $chosen_res $py_file
    fi
}

parse_args() {
    local resolution="16:9"
    local show_preview=false
    local py_file="manimation.py"

    while [[ $# -gt 0 ]]; do
        case $1 in
        -r|--res|--resolution)
            resolution=$2
            shift
            shift
            ;;
        -p|--prev|--preview)
            show_preview=true
            shift
            ;;
        -*|--*) # Match any other option
            echo "Unknown option $1; Exiting..." 1>&2
            exit 1
            ;;
        *) # Match any argument not preceded by '-'; in this case, it will be the filename of the animation
            py_file=$1
            shift
            ;;
        esac
    done 

    echo "$resolution $show_preview $py_file"
}

validate_args() {
    local resolution=$1
    case $resolution in
        16:9|16:10)
            ;;
        *)
            echo "Unknown resolution $resolution. Exiting..." 1>&2
            exit 1
            ;;
    esac

    local py_file=$2
    case $py_file in
        *.py)
            ;;
        *)
            echo "Invalid Manimation received — $py_file. Exiting..." 1>&2
            exit 1
            ;;
    esac
}

extract_file_name() {
    local file=$1
    # Removes the extension of the file
    echo ${file%.*}
}

# Input reading and parsing
read RESOLUTION SHOW_PREVIEW PY_FILE <<< "$(parse_args "$@")"

# Argument validation
validate_args $RESOLUTION $PY_FILE

# Animation rendering
render_manimation $PY_FILE $RESOLUTION $SHOW_PREVIEW

if [ ! -d "./exports" ]; then
    create_export_folder
fi

FILE_TO_SEARCH=$(grep 'class *' $PY_FILE | )
echo $FILE_TO_SEARCH